package Throws;
class Exception
{
	
	void add() throws ArithmeticException
	{ 
		try {
			int a=12;
			if(a>16)
			{
				System.out.println("1");
			}
			
		}
		catch(ArithmeticException a1)
		{
			System.out.println("ArithmeticException handling");
			
		}
		
	}
}

public class Age1 extends Exception 
{
	public static void main(String[] args) {
		Exception e1=new Exception();
		e1.add();
		
	}

}
