package Throws;
class Exception
{
	
	void add() throws ArithmeticException
	{ 
		try {
			int c=1/0;
		}
		catch(ArithmeticException e1)
		{
			System.out.println("handling");
		}
	}
}

public class Age2 
{

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
